name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: ESLint
        run: pnpm lint:ci

      - name: Jest Tests
        run: pnpm test:ci

      - name: Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          start: pnpm start
          wait-on: "http://localhost:8080"
          browser: chrome

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: ./cypress/videos
